# Generated by Django 4.2.9 on 2024-01-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_id', models.IntegerField()),
                ('doctor_id_number', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('patient_id_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appointments.patients')),
            ],
        ),
    ]
