# Generated by Django 4.2.9 on 2024-02-24 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_doctor_6_availability'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Appointments',
            new_name='Appointment',
        ),
        migrations.RenameModel(
            old_name='Patients',
            new_name='Patient',
        ),
    ]
