# Generated by Django 4.2.9 on 2024-02-24 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0009_rename_appointments_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_1_availability',
            name='appointment_id',
        ),
    ]
